on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
      VERSION: ${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Archive Datapack
        uses: thedoctor0/zip-release@master
        with:
          filename: 'datapack.zip'
          exclusions: 'resource/** *.git*'
        
      - name: Archive Resourcepack
        uses: thedoctor0/zip-release@master
        with:
          filename: 'resourcepack.zip'
          directory: 'resource/'
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false

      - name: Upload Datapack
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: './datapack.zip'
          asset_name: ${{ env.REPO_NAME }}_datapack.zip
          asset_content_type: application/zip
        
      - name: Upload Resourcepack
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: './resource/resourcepack.zip'
          asset_name: ${{ env.REPO_NAME }}_resourcepack.zip
          asset_content_type: application/zip
